name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang]

    runs-on: ubuntu-latest

    env:
      CC: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make